kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: false
  ignore_unconnected: false
  set_text_variables:
    - variable: drawn_by
      command: git log -1 --format="%an"
    - variable: git_date
      command: git log -1 --format="%as"
    - variable: git_describe
      command: git describe --always
    - variable: git_url
      command: git config --get remote.origin.url

outputs:
  - name: "print_sch"
    type: pdf_sch_print
    comment: "Print schematic (PDF)"
    options:
      output: schematic.pdf

  - name: BoM
    type: ibom
    comment: "Interactive Bill of Materials (HTML)"
    options:
      output: bom.html
