name: run checks on project

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@v1_k6
        with:
          config: .github/workflows/resources/checks.kibot.yml
          schema: 24V_plc_integration_shield/24V_plc_integration_shield.kicad_sch
          board: 24V_plc_integration_shield/24V_plc_integration_shield.kicad_pcb
