name: use kikit to create documentation
on: [push]
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    container:
      image: yaqwsx/kikit:v1.0.2
    steps:
      - uses: actions/checkout@v2
      - run: cd 24V_plc_integration_shield && kikit present
  run-drc:
    runs-on: ubuntu-latest
    container:
      image: yaqwsx/kikit:v1.0.2
    steps:
      - uses: actions/checkout@v2
      - run: cd 24V_plc_integration_shield && kikit drc run *.kicad_pcb
