---
name: set up webpage with presentation, and tests schema and pcb
on: [push]
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    container:
      image: yaqwsx/kikit:v1.0.2
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p kikit-out kibot-out
      - uses: INTI-CMNB/KiBot@v1_k6
        with:
          # Required - kibot config file
          config: docs.kibot.yml
          # optional - prefix to output defined in config
          dir: kibot-out
          # optional - schematic file
          schema: "24V_plc_integration_shield/24V_plc_integration_shield.kicad_sch"
          # optional - PCB design file
          board: "24V_plc_integration_shield/24V_plc_integration_shield.kicad_pcb"
      - run: >
          kikit present boardpage
            --name 24V_plc_integration_shield
            -d 24V_plc_integration_shield/README.md
            -r kibot-output/*
            -b 24V_plc_integration_shield/24V_plc_integration_shield.kicad_pcb
            kikit-out
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: kikit-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@v1_k6
        with:
          # Required - kibot config file
          config: check.kibot.yml
          # optional - schematic file
          schema: "*/*.kicad_sch"
          # optional - PCB design file
          board: "*/*.kicad_pcb"
